#!/bin/bash

#Length of each fastq file
wc -l fastq/*.fq.gz
#Remove previously made files
rm -r fastqc_out/*fastqc*
#qc check on one pair of reads
fastqc -o fastqc_out -t 3 fastq/Tco-106*

#Unzip zipped output files
unzip fastqc_out/\*.zip -d fastqc_out
